-- IF NOT EXISTS adopts the existing Hibernate schema without recreating tables or sequences.
-- Hibernate validation still rejects incompatible column types or missing mapped columns.
CREATE TABLE IF NOT EXISTS channel_settings (
    channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    description VARCHAR(500),
    channel_type VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    direction VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT channel_settings_channel_type_check CHECK (channel_type IN ('FTP', 'SFTP', 'KAFKA', 'DIRECTORY', 'RABBITMQ')),
    CONSTRAINT channel_settings_direction_check CHECK (direction IN ('INBOUND', 'OUTBOUND'))
);

CREATE TABLE IF NOT EXISTS channel_properties (
    channel_id BIGINT NOT NULL REFERENCES channel_settings(channel_id),
    property_key VARCHAR(255) NOT NULL,
    property_value TEXT,
    PRIMARY KEY (channel_id, property_key)
);

CREATE TABLE IF NOT EXISTS message (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    payload TEXT NOT NULL,
    payload_type VARCHAR(50) NOT NULL,
    source_system VARCHAR(100),
    target_system VARCHAR(100),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT message_direction_check CHECK (direction IN ('INBOUND', 'OUTBOUND')),
    CONSTRAINT message_status_check CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'PROCESSED'))
);

CREATE TABLE IF NOT EXISTS message_metadata (
    metadata_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES message(message_id),
    key VARCHAR(100) NOT NULL,
    value VARCHAR(5000) NOT NULL
);

-- Task remains a mapped entity, even though the example view is disabled.
-- Hibernate's pooled sequence generator uses blocks of 50 IDs.
CREATE SEQUENCE IF NOT EXISTS task_seq START WITH 1 INCREMENT BY 50;
CREATE TABLE IF NOT EXISTS task (
    task_id BIGINT PRIMARY KEY,
    description VARCHAR(300) NOT NULL,
    creation_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    due_date DATE
);
