ALTER TABLE rule_action ADD COLUMN IF NOT EXISTS target_channel_id BIGINT REFERENCES channel_settings(channel_id);
UPDATE rule_action a SET target_channel_id=c.channel_id FROM channel_settings c
WHERE a.action_type='ROUTE' AND a.target_channel=c.name;

CREATE TABLE IF NOT EXISTS rule_source_health (
    rule_id BIGINT NOT NULL REFERENCES rule(rule_id) ON DELETE CASCADE,
    worker_id VARCHAR(160) NOT NULL,
    status VARCHAR(24) NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL,
    error_message TEXT,
    PRIMARY KEY(rule_id,worker_id)
);
CREATE TABLE IF NOT EXISTS worker_container_metric_sample (
    sample_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_pool_id BIGINT NOT NULL REFERENCES rule_worker_pool(worker_pool_id) ON DELETE CASCADE,
    container_id VARCHAR(64) NOT NULL,
    container_name VARCHAR(200) NOT NULL,
    sampled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cpu_percent DOUBLE PRECISION NOT NULL,
    memory_percent DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_container_metric_time ON worker_container_metric_sample(worker_pool_id,container_id,sampled_at);
