ALTER TABLE channel_settings ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE rule ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE rule_action ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE rule_condition ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE rule_worker_pool ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE rule_execution_job ADD COLUMN IF NOT EXISTS configuration_snapshot TEXT;
ALTER TABLE rule_execution_job ADD COLUMN IF NOT EXISTS delivery_started BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE rule_execution_job ADD COLUMN IF NOT EXISTS delivery_uncertain BOOLEAN NOT NULL DEFAULT false;
CREATE TABLE configuration_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor VARCHAR(200) NOT NULL,
    entity_type VARCHAR(200) NOT NULL,
    entity_id BIGINT,
    operation VARCHAR(100) NOT NULL
);
CREATE INDEX configuration_audit_time ON configuration_audit(occurred_at);
-- Expression indexes match the literal, case-insensitive substring filters.
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
CREATE INDEX message_source_search ON message USING gin (lower(source_system) public.gin_trgm_ops);
CREATE INDEX message_target_search ON message USING gin (lower(target_system) public.gin_trgm_ops);
CREATE INDEX rule_job_active_created ON rule_execution_job(status,created_at) WHERE status IN ('PENDING','PROCESSING');
