CREATE TABLE IF NOT EXISTS rule (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    rule_type VARCHAR(255) NOT NULL,
    source_channel_id BIGINT NOT NULL REFERENCES channel_settings(channel_id),
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT rule_rule_type_check CHECK (rule_type IN ('INBOUND', 'OUTBOUND'))
);

CREATE TABLE IF NOT EXISTS rule_condition (
    condition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL REFERENCES rule(rule_id),
    field VARCHAR(100) NOT NULL,
    operator VARCHAR(255) NOT NULL,
    value VARCHAR(1000) NOT NULL,
    logical_operator VARCHAR(255) NOT NULL,
    CONSTRAINT rule_condition_operator_check CHECK (operator IN ('EQUALS', 'CONTAINS', 'REGEX', 'GREATER', 'LESS', 'NOT_EQUALS')),
    CONSTRAINT rule_condition_logical_operator_check CHECK (logical_operator IN ('AND', 'OR'))
);

CREATE TABLE IF NOT EXISTS rule_action (
    action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL REFERENCES rule(rule_id),
    action_type VARCHAR(255) NOT NULL,
    target_channel VARCHAR(200),
    transformation_script TEXT,
    filter_result BOOLEAN,
    metadata_key VARCHAR(100),
    metadata_value VARCHAR(1000),
    priority INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT rule_action_action_type_check CHECK (action_type IN ('ROUTE', 'TRANSFORM', 'FILTER', 'ENRICH'))
);
