CREATE TABLE IF NOT EXISTS rule_worker_pool (
    worker_pool_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    desired_replicas INTEGER NOT NULL,
    min_replicas INTEGER NOT NULL,
    max_replicas INTEGER NOT NULL,
    auto_scale_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    pending_jobs_per_worker INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_rule_worker_pool_name UNIQUE (name)
);

-- Upgrade pools created before autoscaling was introduced.
ALTER TABLE rule_worker_pool ADD COLUMN IF NOT EXISTS auto_scale_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE rule_worker_pool ADD COLUMN IF NOT EXISTS pending_jobs_per_worker INTEGER NOT NULL DEFAULT 50;
ALTER TABLE rule ADD COLUMN IF NOT EXISTS worker_pool_id BIGINT;

-- Hibernate used generated FK names. Inspect the relationship rather than its name
-- to avoid adding a duplicate FK when adopting an existing database.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE contype = 'f' AND conrelid = 'rule'::regclass
          AND confrelid = 'rule_worker_pool'::regclass
          AND conkey = ARRAY[(SELECT attnum FROM pg_attribute
                              WHERE attrelid = 'rule'::regclass AND attname = 'worker_pool_id')]
    ) THEN
        ALTER TABLE rule ADD CONSTRAINT fk_rule_worker_pool
            FOREIGN KEY (worker_pool_id) REFERENCES rule_worker_pool(worker_pool_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS rule_execution_job (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES message(message_id),
    rule_id BIGINT NOT NULL REFERENCES rule(rule_id),
    worker_pool_id BIGINT NOT NULL REFERENCES rule_worker_pool(worker_pool_id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    worker_id VARCHAR(160),
    error_message TEXT,
    result TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    claimed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT rule_execution_job_status_check CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

ALTER TABLE rule_execution_job ADD COLUMN IF NOT EXISTS result TEXT;
ALTER TABLE rule_execution_job ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP(6) WITH TIME ZONE;
