CREATE TABLE IF NOT EXISTS worker_pool_metric_sample (
    sample_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_pool_id BIGINT NOT NULL REFERENCES rule_worker_pool(worker_pool_id),
    sampled_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    cpu_percent DOUBLE PRECISION NOT NULL,
    memory_percent DOUBLE PRECISION NOT NULL
);
